parameters:
    anyt.issue.code.generator.class: Anyt\BugTrackerBundle\IssueCodeGenerator\BasicGenerator
services:
    anyt.issue.code.listener:
        class: Anyt\BugTrackerBundle\EventListener\IssueCodeListener
        arguments: [@anyt.issue.code.generator]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    anyt.issue.note.listener:
        class: Anyt\BugTrackerBundle\EventListener\NoteListener
        tags:
            - { name: doctrine.event_listener, event: onFlush }
    anyt.issue.code.generator:
        class: '%anyt.issue.code.generator.class%'


    anyt.issue.manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - Anyt\BugTrackerBundle\Entity\Issue
            - "@doctrine.orm.entity_manager"
    anyt.form.type.issue.api:
        class:                                      Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %orocrm_account.account.entity.class%
            - @doctrine.orm.entity_manager

    anyt.form.issue.api:
        class:                                      Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["issue", "issue", null]

    anyt.form.handler.issue.api:
        class:                                      Anyt\BugTrackerBundle\Form\Handler\IssueHandler
        scope: request
        arguments:
            - @anyt.form.issue.api
            - @request
            - @doctrine.orm.entity_manager
        tags:
            - { name: oro_tag.tag_manager }