anyt_bugtracker_bundle:
        resource: "@AnytBugTrackerBundle/Controller/"
        type:     annotation
        prefix:   /issue
anyt_bugtracker_bundle_api:
    resource: "@AnytBugTrackerBundle/Resources/config/oro/routing_api.yml"
    type: rest
    prefix: api/rest/{version}
    requirements:
        version:  latest|v1
    defaults:
        version:  latest
